### ISSUE TITLE
STAC's main.py Stuck at 0% During Model Update on Windows

### ISSUE THREAD

**Issue by liem0106** [SafaMessaoud/S2AC-Energy-Based-RL-with-Stein-Soft-Actor-Critic#3]
(m) C:\Users\Administrator\mjccode\S2AC-Energy-Based-RL-with-Stein-Soft-Actor-Critic-main>python ./STAC/main.py --env Walker2d-v2 --max_experiment_steps 5e5 --seed 33 --actor svgd_p0_pram --train_acti
on_selection random --test_action_selection softmax --gpu_id 0 --svgd_steps 3 --a_c 0.2 --a_a 0.2
running build_ext
########################################## Hyper-Parameters ##########################################
Debugging:  False
GPU ID:  0
Environment:  Walker2d-v2
Algorithm:  svgd_p0_pram
Hidden layer size:  256
Critic's Number of layers:  2
Critic's Activation:  <class 'torch.nn.modules.activation.ELU'>
Discount Factor (Gamma):  0.99
Entropy coefficient (Alpha Critic):  0.2
Entropy coefficient (Alpha Actor):  0.2
Replay Buffer size:  1000000.0
Load Replay Buffer:  False
Experiment's steps:  500000.0
Initial Exploration steps:  10000
Number test episodes:  10
Start Updating models after step:  1000
Update models every:  50
Max Environment steps:  1000
Polyak target update rate:  0.995
Critic's learning rate:  0.001
Batch size:  100
Train action selection:  random
Test action selection:  softmax
Number of particles for SVGD:  10
SVGD learning Rate:  0.1
Number of SVGD steps:  3
SVGD initial distribution's variance:  0.5
SVGD's kernel variance:  None
Plot format:  pdf
Statistics Collection frequency:  400
Collect Statistics after:  0
Seed:  33
Device:  cuda:0
Project Name:  dbg_mlpDec_19_2024_09_47_53_svgd_p0_pram_Walker2d-v2_tnas_random_ttas_softmax_a_c_0.2_a_a_0.2_bs_100_gamma_0.99_seed_33_ntep_10_ss_3_sp_10_slr_0.1_sks_None_4_expr_500000.0_explr_10000_u
pdt_1000_PID_31524
Experiment Importance:  dbg
Experiment PID:  31524

:\envs\m\lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.                                                                                 | 0/10 [00:00<?, ?it/s]
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\envs\m\lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

####### --actor:  svgd_p0_pram  --ep_return:  2.360685024850477  --ep_length:  37

 10%|████████████████▎                                                                                                                                                  | 1/10 [00:00<0
####### --actor:  svgd_p0_pram  --ep_return:  168.8445353064336  --ep_length:  97

 20%|████████████████████████████████▌
####### --actor:  svgd_p0_pram  --ep_return:  7.079600592754759  --ep_length:  26

 30%|████████████████████████████████████████████████▉
####### --actor:  svgd_p0_pram  --ep_return:  107.46690564710705  --ep_length:  196

 40%|█████████████████████████████████████████████████████████████████▏
####### --actor:  svgd_p0_pram  --ep_return:  21.130253355698414  --ep_length:  90

 50%|█████████████████████████████████████████████████████████████████████████████████▌
####### --actor:  svgd_p0_pram  --ep_return:  1.0585451176207339  --ep_length:  22

 60%|█████████████████████████████████████████████████████████████████████████████████████████████████
####### --actor:  svgd_p0_pram  --ep_return:  11.591501324476342  --ep_length:  310:02,  1.62it/s]

 70%|█████████████████████████████████████████████████████████████████████████████████████████████████
####### --actor:  svgd_p0_pram  --ep_return:  15.572461451905388  --ep_length:  85 | 7/10 [00:04<00:01,  2.12it/s]

 80%|█████████████████████████████████████████████████████████████████████████████████████████████████
####### --actor:  svgd_p0_pram  --ep_return:  178.02929816131717  --ep_length:  169                 | 8/10 [00:05<00:01,  1.85it/s]

 90%|█████████████████████████████████████████████████████████████████████████████████████████████████
####### --actor:  svgd_p0_pram  --ep_return:  5.993229873228548  --ep_length:  23 ████████▋                | 9/10 [00:06<00:00,  1.36it/s]

100%|█████████████████████████████████████████████████████████████████████████████████████████████████
█████████████████████████████████████████████████████████████████| 10/10 [00:06<00:00,  1.54it/s]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\envs\m\lib\threading.py", line 980, in _bootstrap_inner
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\envs\m\lib\threading.py", line 980, in _bootstrap_inner
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\envs\m\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
self.run()  File "C:\envs\m\lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 233, in run
self.run()

  File "C:\envs\m\lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 233, in run
  0%|                                                                                                                                                                           | 0/10 [00:00<?, ?it/s]
    self._record_writer.write(data)    self._record_writer.write(data)    riter.py", line 233, in run

self._record_writer.write(data)  File "C:\envs\m\lib\site-packages\tensorboard\summary\writer\record_writer.py", line 40, in write
  File "C:\envs\m\lib\site-packages\tensorboard\summary\writer\record_writer.py", line 40, in write

  File "C:\envs\m\lib\site-packages\tensorboard\summary\writer\record_writer.py", line 40, in write
    self._writer.write(header + header_crc + data + footer_crc)
self._writer.write(header + header_crc + data + footer_crc)self._writer.write(header + header_crc + data + footer_crc)  File "C:\envs\m\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 103
, in write

  File "C:\envs\m\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 103, in write
  File "C:\envs\m\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 103, in write
            self._prewrite_check()self._prewrite_check()self._prewrite_check()

  File "C:\envs\m\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 88, in _prewrite_check
  File "C:\envs\m\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 88, in _prewrite_check
  File "C:\envs\m\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 88, in _prewrite_check
        self._writable_file = _pywrap_file_io.WritableFile(self._writable_file = _pywrap_file_io.WritableFile(

self._writable_file = _pywrap_file_io.WritableFile(UnicodeDecodeErrorUnicodeDecodeError
: : UnicodeDecodeError'utf-8' codec can't decode byte 0xd5 in position 382: invalid continuation byte'utf-8' codec can't decode byte 0xd5 in position 381: invalid continuation byte:

'utf-8' codec can't decode byte 0xd5 in position 382: invalid continuation byte

####### --actor:  svgd_p0_pram  --ep_return:  0.4314946452465792  --ep_length:  17

 10%|████████████████▎                                                                                                                                                  | 1/10 [00:00<0
####### --actor:  svgd_p0_pram  --ep_return:  -4.68861328140238  --ep_length:  21

 20%|████████████████████████████████▌
####### --actor:  svgd_p0_pram  --ep_return:  -3.8787027602253934  --ep_length:  16

 40%|█████████████████████████████████████████████████████████████████▏
####### --actor:  svgd_p0_pram  --ep_return:  -1.907726193559442  --ep_length:  32

 50%|█████████████████████████████████████████████████████████████████████████████████▌
####### --actor:  svgd_p0_pram  --ep_return:  -1.7134672770835193  --ep_length:  15

 60%|█████████████████████████████████████████████████████████████████████████████████████████████████
####### --actor:  svgd_p0_pram  --ep_return:  0.24814223689482995  --ep_length:  18:00,  5.58it/s]

 70%|█████████████████████████████████████████████████████████████████████████████████████████████████
####### --actor:  svgd_p0_pram  --ep_return:  7.539772644131999  --ep_length:  43  | 7/10 [00:01<00:00,  5.70it/s]

 80%|█████████████████████████████████████████████████████████████████████████████████████████████████
####### --actor:  svgd_p0_pram  --ep_return:  2.607892071397364  --ep_length:  34                   | 8/10 [00:01<00:00,  4.97it/s]

 90%|█████████████████████████████████████████████████████████████████████████████████████████████████
####### --actor:  svgd_p0_pram  --ep_return:  10.136186072422776  --ep_length:  24████████▋                | 9/10 [00:01<00:00,  4.33it/s]

100%|█████████████████████████████████████████████████████████████████████████████████████████████████
█████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  4.91it/s]
Exception in thread Thread-12:
Traceback (most recent call last):
  File "C:\envs\m\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\envs\m\lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 233, in run
    self._record_writer.write(data)
  File "C:\envs\m\lib\site-packages\tensorboard\summary\writer\record_writer.py", line 40, in write
    self._writer.write(header + header_crc + data + footer_crc)
  File "C:\envs\m\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 103, in write
    self._prewrite_check()
  File "C:\envs\m\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 88, in _prewrite_check
    self._writable_file = _pywrap_file_io.WritableFile(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 376: invalid continuation byte
Exception in thread Thread-15:
Traceback (most recent call last):
  File "C:\envs\m\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\envs\m\lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 233, in run
    self._record_writer.write(data)
  File "C:\envs\m\lib\site-packages\tensorboard\summary\writer\record_writer.py", line 40, in write
    self._writer.write(header + header_crc + data + footer_crc)
  File "C:\envs\m\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 103, in write
    self._prewrite_check()
  File "C:\envs\m\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 88, in _prewrite_check
    self._writable_file = _pywrap_file_io.WritableFile(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 377: invalid continuation byte
  0%|▏                                                                                                                                                          | 793/500000 [00:08<1:31:03, 91.37it/s]
####### --actor:  svgd_p0_pram  --ep_return:  7.4460816869521365  --ep_length:  58                                                                                              | 0/10 [00:00<?, ?it/s]

 10%|████████████████▎                                                                                                                                                  | 1/10 [00:00<0
####### --actor:  svgd_p0_pram  --ep_return:  2.0005528155293755  --ep_length:  28

 20%|████████████████████████████████▌
####### --actor:  svgd_p0_pram  --ep_return:  9.555254297844401  --ep_length:  70

 30%|████████████████████████████████████████████████▉
####### --actor:  svgd_p0_pram  --ep_return:  6.935647794782363  --ep_length:  52

 40%|█████████████████████████████████████████████████████████████████▏
####### --actor:  svgd_p0_pram  --ep_return:  -0.3547766001607493  --ep_length:  24

 50%|█████████████████████████████████████████████████████████████████████████████████▌
####### --actor:  svgd_p0_pram  --ep_return:  42.03155173335841  --ep_length:  79

 60%|█████████████████████████████████████████████████████████████████████████████████████████████████
####### --actor:  svgd_p0_pram  --ep_return:  14.985033506634496  --ep_length:  790:01,  2.31it/s]

 70%|█████████████████████████████████████████████████████████████████████████████████████████████████
####### --actor:  svgd_p0_pram  --ep_return:  7.941269186129527  --ep_length:  49  | 7/10 [00:02<00:01,  2.18it/s]

 80%|█████████████████████████████████████████████████████████████████████████████████████████████████
####### --actor:  svgd_p0_pram  --ep_return:  2.1596697418465762  --ep_length:  22                  | 8/10 [00:03<00:00,  2.23it/s]

 90%|█████████████████████████████████████████████████████████████████████████████████████████████████
####### --actor:  svgd_p0_pram  --ep_return:  18.66795265399557  --ep_length:  119████████▋                | 9/10 [00:03<00:00,  2.89it/s]

100%|█████████████████████████████████████████████████████████████████████████████████████████████████
█████████████████████████████████████████████████████████████████| 10/10 [00:04<00:00,  2.31it/s]

####### --actor:  svgd_p0_pram  --ep_return:  -0.17917353477175718  --ep_length:  21                                                                                            | 0/10 [00:00<?, ?it/s]

 10%|████████████████▎                                                                                                                                                  | 1/10 [00:00<0
####### --actor:  svgd_p0_pram  --ep_return:  -2.7396409990416624  --ep_length:  25

 20%|████████████████████████████████▌
####### --actor:  svgd_p0_pram  --ep_return:  9.795335390113024  --ep_length:  37

 30%|████████████████████████████████████████████████▉
####### --actor:  svgd_p0_pram  --ep_return:  -5.22893733344769  --ep_length:  20

 40%|█████████████████████████████████████████████████████████████████▏
####### --actor:  svgd_p0_pram  --ep_return:  20.09193683418621  --ep_length:  59

 50%|█████████████████████████████████████████████████████████████████████████████████▌
####### --actor:  svgd_p0_pram  --ep_return:  1.7965624492492815  --ep_length:  27

 60%|█████████████████████████████████████████████████████████████████████████████████████████████████
####### --actor:  svgd_p0_pram  --ep_return:  7.39708388236931  --ep_length:  20<00:01,  3.61it/s]

 70%|█████████████████████████████████████████████████████████████████████████████████████████████████
####### --actor:  svgd_p0_pram  --ep_return:  11.632928030561152  --ep_length:  30 | 7/10 [00:01<00:00,  4.33it/s]

 80%|█████████████████████████████████████████████████████████████████████████████████████████████████
####### --actor:  svgd_p0_pram  --ep_return:  2.0083057236228976  --ep_length:  21                  | 8/10 [00:01<00:00,  4.20it/s]

 90%|█████████████████████████████████████████████████████████████████████████████████████████████████
####### --actor:  svgd_p0_pram  --ep_return:  9.59293013324289  --ep_length:  38█████████▋                | 9/10 [00:02<00:00,  4.02it/s]

100%|█████████████████████████████████████████████████████████████████████████████████████████████████
█████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  4.04it/s]
  0%|▎                                                                                                                                                          | 965/500000 [00:15<2:44:29, 50.56it/s]
######################## Starting models update ########################
Exception in thread Thread-22:
Traceback (most recent call last):
  File "C:\envs\m\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\envs\m\lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 233, in run
    self._record_writer.write(data)
  File "C:\envs\m\lib\site-packages\tensorboard\summary\writer\record_writer.py", line 40, in write
    self._writer.write(header + header_crc + data + footer_crc)
  File "C:\envs\m\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 103, in write
    self._prewrite_check()
  File "C:\envs\m\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 88, in _prewrite_check
    self._writable_file = _pywrap_file_io.WritableFile(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 364: invalid continuation byte
Exception in thread Thread-25:
Traceback (most recent call last):
  File "C:\envs\m\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\envs\m\lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 233, in run
    self._record_writer.write(data)
  File "C:\envs\m\lib\site-packages\tensorboard\summary\writer\record_writer.py", line 40, in write
    self._writer.write(header + header_crc + data + footer_crc)
  File "C:\envs\m\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 103, in write
    self._prewrite_check()
  File "C:\envs\m\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 88, in _prewrite_check
    self._writable_file = _pywrap_file_io.WritableFile(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 365: invalid continuation byte
  0%|▎                                                                                                                                                          | 965/500000 [00:30<2:44:29, 50.56it/s]

My Computer Configuration:
CPU: 12th Gen Intel Core i9-12900K
RAM: 128GB
GPU: NVIDIA GeForce GTX 4090
VRAM：24G
Storage: 4T SSD
Operating System: Windows server 2019 standard

When I run main.py, the progress bar gets stuck at 'starting model update.' I have checked that both GPU and CPU memory are sufficient, but I don't know what the problem might be. Could you provide some troubleshooting directions?And it keeps reporting a UnicodeDecodeError, but I found that it doesn't seem to affect the process.
Looking forward to your reply. Thank u！

**Comment by AIDefender** [comment]
You may comment the line leading to UnicodeDecodeError. It is only for logging uses and does not effect the training. When the program gets stuck, can you Ctrl+C (Interrupt) training and see in which step it stucks?

**Comment by liem0106** [comment]
Okay, I will try commenting out the lines that cause the error. I think the progress bar is stuck because I can't use Ctrl+C to interrupt the training.

**Comment by AIDefender** [comment]
Then you may use some single-step debug tools or print debugging to check which step does the program get stuck.

**Comment by liem0106** [comment]
Okay, thank you for your suggestion. I would also like to ask, what is the typical GPU usage when the program is running? Mine is using about 7GB, and if there's a significant difference, it might be that the model hasn't loaded completely.

**Comment by liem0106** [comment]
I fixed the UTF-8 issue by changing the TensorBoard version to 2.10.0. Also, I found that the line self.tb_logger.add_scalars('smoothness/q_score_detailed', {'Mean': np.mean(q_score_mean), 'Min': np.mean(q_score_min), 'Max': np.mean(q_score_max)}, itr) wasn't generating events in TensorBoard because there was an extra space in 'Mean '. After I removed all those extra spaces, it started running smoothly!
